apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: y1doe0cub-nodejs
  janus-idp.io/tekton: y1doe0cub-nodejs
  backstage.io/kubernetes-id: y1doe0cub-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y1doe0cub-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
